### ISSUE TITLE
排查某些包的文档为什么出不来

### ISSUE THREAD

**Issue by sorrycc** [spmjs/spm-doc-server#2]
http://spmjs.io:3009/docs/alice-button-dropdown/latest/ 可以
http://docs.spmjs.io/alice-button-dropdown/latest/ 不行

相同的问题还有 tipbox 和 step 。

**Comment by sorrycc** [comment]
http://spmjs.io:3009/docs/aliceui.org/latest/ 可以
http://docs.spmjs.io/aliceui.org/latest/ 不可以

**Comment by afc163** [comment]
原来可以的，而且没更新过。

**Comment by sorrycc** [comment]
serve-spm 版本的问题，都可以访问了。
